[project]
name = "beeper-mcp"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beeper-python>=0.1.1",
    "mcp>=1.6.0",
]
